lint:
  rules:
    no_default: true

    add:
      - MESSAGE_NAMES_UPPER_CAMEL_CASE
      - SERVICE_NAMES_UPPER_CAMEL_CASE
      - ENUM_NAMES_UPPER_CAMEL_CASE
      - ENUM_VALUE_NAMES_UPPER_SNAKE_CASE
      - MESSAGE_FIELD_NAMES_LOWER_CAMEL_CASE
  